spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jspdb6
    password: 1234
    username: root

mybatis:
  mapper-locations: mybatis/**/*.xml
  type-aliases-package: com.itwill.test.*
  configuration:
    map-underscore-to-camel-case: true
